# Generated by Django 3.2.7 on 2021-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
