# Generated by Django 3.2.7 on 2021-09-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
